version: "3.9"
services:
  ftp:
    image: bogem/ftp
    ports:
      - "20:20"
      - "21:21"
      - "47400-47470:47400-47470"
    volumes:
      - /tmp/ftp:/home/vsftpd
    environment:
      - FTP_USER=ftp
      - FTP_PASS=ftp
      - PASV_ADDRESS=172.17.0.1
  redis:
    image: redis
    ports:
      - "6379:6379"
  minio:
    image: minio/minio:RELEASE.2020-10-28T08-16-50Z-38-g7482aa978
    command: ["minio", "server", "/data"]
    ports:
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=usertex
      - MINIO_ROOT_PASSWORD=passwdtex
